CREATE TABLE IF NOT EXISTS users
(
    user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(40) NOT NULL,
    email   VARCHAR(40) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS items
(
    item_id     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(40)  NOT NULL,
    description VARCHAR(200) NOT NULL,
    available   BOOLEAN      NOT NULL DEFAULT true,
    owner_id    INT          NOT NULL REFERENCES users (user_id),
    request     INT REFERENCES requests (request_id)
);

CREATE TABLE IF NOT EXISTS booking
(
    booking_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_time TIMESTAMP WITH TIME ZONE NOT NULL,
    end_time   TIMESTAMP WITH TIME ZONE NOT NULL,
    item_id    INT REFERENCES items (item_id),
    booker_id  INT REFERENCES users (user_id),
    status     VARCHAR                  NOT NULL
);

CREATE TABLE IF NOT EXISTS comment
(
    comment_id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text_comment VARCHAR(500)                   NOT NULL,
    item_id      INT REFERENCES items (item_id) NOT NULL,
    author_id    INT REFERENCES users (user_id) NOT NULL,
    created_time TIMESTAMP WITH TIME ZONE       NOT NULL
);

CREATE TABLE IF NOT EXISTS requests
(
    request_id     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description    VARCHAR(200)             NOT NULL,
    "requester_id" INT REFERENCES users (user_id),
    created_time   TIMESTAMP WITH TIME ZONE NOT NULL
);